<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductList(){
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where($queryBuilder->expr()->isNull('c.deleted'));
        $queryBuilder->orderBy('c.id', 'desc');
        return $queryBuilder->getQuery()->getResult();
    }
}
