imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: lt
    app.locales: lt|en
    app.path.product_images: /uploads/images/products
    app.path.part_images: /uploads/images/parts

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Auth Configuration
knpu_oauth2_client:
    clients:
        facebook_main:
            type: facebook
            client_id: "%client_id%"
            client_secret: "%client_secret%"
            redirect_route: connect_check
            redirect_params: {}
            graph_api_version: v2.10

# Doctrine Migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

# Doctrine extensions
stof_doctrine_extensions:
    default_locale: lt
    orm:
        default:
            timestampable: true
            softdeleteable: true

# EasyAdmin
easy_admin:
    site_name: 'EnergyShake'
    list_actions: ['edit', 'delete']
    list:
        title: '%%entity_label%%'
    edit:
        title: '%%entity_label%%'
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'admin.products'
            list:
                fields: ['id', 'title', 'price', { property: 'image', type: 'image', base_path: '%app.path.product_images%' }, 'parts']
            show:
                fields: ['id', 'title', 'price', { property: 'image', type: 'image', base_path: '%app.path.product_images%' }, 'parts']
            form:
                fields: ['title', 'description', 'price', { property: 'imageFile', type: 'file' }, 'parts']
        User:
            class: AppBundle\Entity\User
            label: 'admin.users'
            list:
                fields: ['id', 'username', 'email']
            edit:
                fields: ['username', 'name', 'surname', 'email', 'roles']
        Part:
            class: AppBundle\Entity\Part
            label: 'admin.parts'
            list:
                fields: ['id', 'title', 'description', { property: 'image', type: 'image', base_path: '%app.path.part_images%' }, 'products']
            show:
                fields: ['id', 'title', 'description', { property: 'image', type: 'image', base_path: '%app.path.part_images%' }, 'products']
            form:
                fields: ['title', 'description', { property: 'imageFile', type: 'file' }, 'products']
    design:
        menu:
            - { entity: 'User', icon: 'users' }
            - { entity: 'Product', icon: 'cube' }
            - { entity: 'Part', icon: 'cubes' }
        brand_color: '#000'
        assets:
            favicon: '/assets/images/favicon.png'

# Vich Uploader
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/products'
        part_images:
            uri_prefix:         '%app.path.part_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/parts'